nelmio_api_doc:
    documentation:
        info:
            title: Gizer Test API
            description: GizerTestAPI
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/  # Accepts routes under /api except /api/doc
